//CrimsonTheme.kt
package mt.edu.mcast.webapitutorial_ktor.ui.theme
import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme

val CrimsonLightScheme = lightColorScheme(
    primary = crimsonprimaryLight,
    onPrimary = crimsononPrimaryLight,
    primaryContainer = crimsonprimaryContainerLight,
    onPrimaryContainer = crimsononPrimaryContainerLight,
    secondary = crimsonsecondaryLight,
    onSecondary = crimsononSecondaryLight,
    secondaryContainer = crimsonsecondaryContainerLight,
    onSecondaryContainer = crimsononSecondaryContainerLight,
    tertiary = crimsontertiaryLight,
    onTertiary = crimsononTertiaryLight,
    tertiaryContainer = crimsontertiaryContainerLight,
    onTertiaryContainer = crimsononTertiaryContainerLight,
    error = crimsonerrorLight,
    onError = crimsononErrorLight,
    errorContainer = crimsonerrorContainerLight,
    onErrorContainer = crimsononErrorContainerLight,
    background = crimsonbackgroundLight,
    onBackground = crimsononBackgroundLight,
    surface = crimsonsurfaceLight,
    onSurface = crimsononSurfaceLight,
    surfaceVariant = crimsonsurfaceVariantLight,
    onSurfaceVariant = crimsononSurfaceVariantLight,
    outline = crimsonoutlineLight,
    outlineVariant = crimsonoutlineVariantLight,
    scrim = crimsonscrimLight,
    inverseSurface = crimsoninverseSurfaceLight,
    inverseOnSurface = crimsoninverseOnSurfaceLight,
    inversePrimary = crimsoninversePrimaryLight,
    surfaceDim = crimsonsurfaceDimLight,
    surfaceBright = crimsonsurfaceBrightLight,
    surfaceContainerLowest = crimsonsurfaceContainerLowestLight,
    surfaceContainerLow = crimsonsurfaceContainerLowLight,
    surfaceContainer = crimsonsurfaceContainerLight,
    surfaceContainerHigh = crimsonsurfaceContainerHighLight,
    surfaceContainerHighest = crimsonsurfaceContainerHighestLight,
)

val CrimsonDarkScheme = darkColorScheme(
    primary = crimsonprimaryDark,
    onPrimary = crimsononPrimaryDark,
    primaryContainer = crimsonprimaryContainerDark,
    onPrimaryContainer = crimsononPrimaryContainerDark,
    secondary = crimsonsecondaryDark,
    onSecondary = crimsononSecondaryDark,
    secondaryContainer = crimsonsecondaryContainerDark,
    onSecondaryContainer = crimsononSecondaryContainerDark,
    tertiary = crimsontertiaryDark,
    onTertiary = crimsononTertiaryDark,
    tertiaryContainer = crimsontertiaryContainerDark,
    onTertiaryContainer = crimsononTertiaryContainerDark,
    error = crimsonerrorDark,
    onError = crimsononErrorDark,
    errorContainer = crimsonerrorContainerDark,
    onErrorContainer = crimsononErrorContainerDark,
    background = crimsonbackgroundDark,
    onBackground = crimsononBackgroundDark,
    surface = crimsonsurfaceDark,
    onSurface = crimsononSurfaceDark,
    surfaceVariant = crimsonsurfaceVariantDark,
    onSurfaceVariant = crimsononSurfaceVariantDark,
    outline = crimsonoutlineDark,
    outlineVariant = crimsonoutlineVariantDark,
    scrim = crimsonscrimDark,
    inverseSurface = crimsoninverseSurfaceDark,
    inverseOnSurface = crimsoninverseOnSurfaceDark,
    inversePrimary = crimsoninversePrimaryDark,
    surfaceDim = crimsonsurfaceDimDark,
    surfaceBright = crimsonsurfaceBrightDark,
    surfaceContainerLowest = crimsonsurfaceContainerLowestDark,
    surfaceContainerLow = crimsonsurfaceContainerLowDark,
    surfaceContainer = crimsonsurfaceContainerDark,
    surfaceContainerHigh = crimsonsurfaceContainerHighDark,
    surfaceContainerHighest = crimsonsurfaceContainerHighestDark,
)
