//MonoTheme.kt
package mt.edu.mcast.webapitutorial_ktor.ui.theme
import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme

val MonoLightScheme = lightColorScheme(
    primary = monoprimaryLight,
    onPrimary = monoonPrimaryLight,
    primaryContainer = monoprimaryContainerLight,
    onPrimaryContainer = monoonPrimaryContainerLight,
    secondary = monosecondaryLight,
    onSecondary = monoonSecondaryLight,
    secondaryContainer = monosecondaryContainerLight,
    onSecondaryContainer = monoonSecondaryContainerLight,
    tertiary = monotertiaryLight,
    onTertiary = monoonTertiaryLight,
    tertiaryContainer = monotertiaryContainerLight,
    onTertiaryContainer = monoonTertiaryContainerLight,
    error = monoerrorLight,
    onError = monoonErrorLight,
    errorContainer = monoerrorContainerLight,
    onErrorContainer = monoonErrorContainerLight,
    background = monobackgroundLight,
    onBackground = monoonBackgroundLight,
    surface = monosurfaceLight,
    onSurface = monoonSurfaceLight,
    surfaceVariant = monosurfaceVariantLight,
    onSurfaceVariant = monoonSurfaceVariantLight,
    outline = monooutlineLight,
    outlineVariant = monooutlineVariantLight,
    scrim = monoscrimLight,
    inverseSurface = monoinverseSurfaceLight,
    inverseOnSurface = monoinverseOnSurfaceLight,
    inversePrimary = monoinversePrimaryLight,
    surfaceDim = monosurfaceDimLight,
    surfaceBright = monosurfaceBrightLight,
    surfaceContainerLowest = monosurfaceContainerLowestLight,
    surfaceContainerLow = monosurfaceContainerLowLight,
    surfaceContainer = monosurfaceContainerLight,
    surfaceContainerHigh = monosurfaceContainerHighLight,
    surfaceContainerHighest = monosurfaceContainerHighestLight,
)

val MonoDarkScheme = darkColorScheme(
    primary = monoprimaryDark,
    onPrimary = monoonPrimaryDark,
    primaryContainer = monoprimaryContainerDark,
    onPrimaryContainer = monoonPrimaryContainerDark,
    secondary = monosecondaryDark,
    onSecondary = monoonSecondaryDark,
    secondaryContainer = monosecondaryContainerDark,
    onSecondaryContainer = monoonSecondaryContainerDark,
    tertiary = monotertiaryDark,
    onTertiary = monoonTertiaryDark,
    tertiaryContainer = monotertiaryContainerDark,
    onTertiaryContainer = monoonTertiaryContainerDark,
    error = monoerrorDark,
    onError = monoonErrorDark,
    errorContainer = monoerrorContainerDark,
    onErrorContainer = monoonErrorContainerDark,
    background = monobackgroundDark,
    onBackground = monoonBackgroundDark,
    surface = monosurfaceDark,
    onSurface = monoonSurfaceDark,
    surfaceVariant = monosurfaceVariantDark,
    onSurfaceVariant = monoonSurfaceVariantDark,
    outline = monooutlineDark,
    outlineVariant = monooutlineVariantDark,
    scrim = monoscrimDark,
    inverseSurface = monoinverseSurfaceDark,
    inverseOnSurface = monoinverseOnSurfaceDark,
    inversePrimary = monoinversePrimaryDark,
    surfaceDim = monosurfaceDimDark,
    surfaceBright = monosurfaceBrightDark,
    surfaceContainerLowest = monosurfaceContainerLowestDark,
    surfaceContainerLow = monosurfaceContainerLowDark,
    surfaceContainer = monosurfaceContainerDark,
    surfaceContainerHigh = monosurfaceContainerHighDark,
    surfaceContainerHighest = monosurfaceContainerHighestDark,
)
