//SecretTheme.kt
package mt.edu.mcast.webapitutorial_ktor.ui.theme
import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme

val SecretLightScheme = lightColorScheme(
    primary = secretprimaryLight,
    onPrimary = secretonPrimaryLight,
    primaryContainer = secretprimaryContainerLight,
    onPrimaryContainer = secretonPrimaryContainerLight,
    secondary = secretsecondaryLight,
    onSecondary = secretonSecondaryLight,
    secondaryContainer = secretsecondaryContainerLight,
    onSecondaryContainer = secretonSecondaryContainerLight,
    tertiary = secrettertiaryLight,
    onTertiary = secretonTertiaryLight,
    tertiaryContainer = secrettertiaryContainerLight,
    onTertiaryContainer = secretonTertiaryContainerLight,
    error = secreterrorLight,
    onError = secretonErrorLight,
    errorContainer = secreterrorContainerLight,
    onErrorContainer = secretonErrorContainerLight,
    background = secretbackgroundLight,
    onBackground = secretonBackgroundLight,
    surface = secretsurfaceLight,
    onSurface = secretonSurfaceLight,
    surfaceVariant = secretsurfaceVariantLight,
    onSurfaceVariant = secretonSurfaceVariantLight,
    outline = secretoutlineLight,
    outlineVariant = secretoutlineVariantLight,
    scrim = secretscrimLight,
    inverseSurface = secretinverseSurfaceLight,
    inverseOnSurface = secretinverseOnSurfaceLight,
    inversePrimary = secretinversePrimaryLight,
    surfaceDim = secretsurfaceDimLight,
    surfaceBright = secretsurfaceBrightLight,
    surfaceContainerLowest = secretsurfaceContainerLowestLight,
    surfaceContainerLow = secretsurfaceContainerLowLight,
    surfaceContainer = secretsurfaceContainerLight,
    surfaceContainerHigh = secretsurfaceContainerHighLight,
    surfaceContainerHighest = secretsurfaceContainerHighestLight,
)

val SecretDarkScheme = darkColorScheme(
    primary = secretprimaryDark,
    onPrimary = secretonPrimaryDark,
    primaryContainer = secretprimaryContainerDark,
    onPrimaryContainer = secretonPrimaryContainerDark,
    secondary = secretsecondaryDark,
    onSecondary = secretonSecondaryDark,
    secondaryContainer = secretsecondaryContainerDark,
    onSecondaryContainer = secretonSecondaryContainerDark,
    tertiary = secrettertiaryDark,
    onTertiary = secretonTertiaryDark,
    tertiaryContainer = secrettertiaryContainerDark,
    onTertiaryContainer = secretonTertiaryContainerDark,
    error = secreterrorDark,
    onError = secretonErrorDark,
    errorContainer = secreterrorContainerDark,
    onErrorContainer = secretonErrorContainerDark,
    background = secretbackgroundDark,
    onBackground = secretonBackgroundDark,
    surface = secretsurfaceDark,
    onSurface = secretonSurfaceDark,
    surfaceVariant = secretsurfaceVariantDark,
    onSurfaceVariant = secretonSurfaceVariantDark,
    outline = secretoutlineDark,
    outlineVariant = secretoutlineVariantDark,
    scrim = secretscrimDark,
    inverseSurface = secretinverseSurfaceDark,
    inverseOnSurface = secretinverseOnSurfaceDark,
    inversePrimary = secretinversePrimaryDark,
    surfaceDim = secretsurfaceDimDark,
    surfaceBright = secretsurfaceBrightDark,
    surfaceContainerLowest = secretsurfaceContainerLowestDark,
    surfaceContainerLow = secretsurfaceContainerLowDark,
    surfaceContainer = secretsurfaceContainerDark,
    surfaceContainerHigh = secretsurfaceContainerHighDark,
    surfaceContainerHighest = secretsurfaceContainerHighestDark,
)