//EmeraldColor.kt
package com.strahinja0019.manhwasync.ui.theme
import androidx.compose.ui.graphics.Color

val emeraldprimaryLight = Color(0xFF4C662B)
val emeraldonPrimaryLight = Color(0xFFFFFFFF)
val emeraldprimaryContainerLight = Color(0xFFCDEDA3)
val emeraldonPrimaryContainerLight = Color(0xFF354E16)
val emeraldsecondaryLight = Color(0xFF386663)
val emeraldonSecondaryLight = Color(0xFFFFFFFF)
val emeraldsecondaryContainerLight = Color(0xFFDCE7C8)
val emeraldonSecondaryContainerLight = Color(0xFF1F4E4B)
val emeraldtertiaryLight = Color(0xFF586249)
val emeraldonTertiaryLight = Color(0xFFFFFFFF)
val emeraldtertiaryContainerLight = Color(0xFFBCECE7)
val emeraldonTertiaryContainerLight = Color(0xFF404A33)
val emeralderrorLight = Color(0xFFBA1A1A)
val emeraldonErrorLight = Color(0xFFFFFFFF)
val emeralderrorContainerLight = Color(0xFFFFDAD6)
val emeraldonErrorContainerLight = Color(0xFF93000A)
val emeraldbackgroundLight = Color(0xFFF9FAEF)
val emeraldonBackgroundLight = Color(0xFF1A1C16)
val emeraldsurfaceLight = Color(0xFFF9FAEF)
val emeraldonSurfaceLight = Color(0xFF1A1C16)
val emeraldsurfaceVariantLight = Color(0xFFE1E4D5)
val emeraldonSurfaceVariantLight = Color(0xFF44483D)
val emeraldoutlineLight = Color(0xFF75796C)
val emeraldoutlineVariantLight = Color(0xFFC5C8BA)
val emeraldscrimLight = Color(0xFF000000)
val emeraldinverseSurfaceLight = Color(0xFF2F312A)
val emeraldinverseOnSurfaceLight = Color(0xFFF1F2E6)
val emeraldinversePrimaryLight = Color(0xFFB1D18A)
val emeraldsurfaceDimLight = Color(0xFFDADBD0)
val emeraldsurfaceBrightLight = Color(0xFFF9FAEF)
val emeraldsurfaceContainerLowestLight = Color(0xFFFFFFFF)
val emeraldsurfaceContainerLowLight = Color(0xFFF3F4E9)
val emeraldsurfaceContainerLight = Color(0xFFEEEFE3)
val emeraldsurfaceContainerHighLight = Color(0xFFE8E9DE)
val emeraldsurfaceContainerHighestLight = Color(0xFFE2E3D8)

val emeraldprimaryDark = Color(0xFFB1D18A)
val emeraldonPrimaryDark = Color(0xFF1F3701)
val emeraldprimaryContainerDark = Color(0xFF354E16)
val emeraldonPrimaryContainerDark = Color(0xFFCDEDA3)
val emeraldsecondaryDark = Color(0xFF6DA6A0)
val emeraldonSecondaryDark = Color(0xFF003735)
val emeraldsecondaryContainerDark = Color(0xFF1F4E4B)
val emeraldonSecondaryContainerDark = Color(0xFFDCE7C8)
val emeraldtertiaryDark = Color(0xFFBFCBAD)
val emeraldonTertiaryDark = Color(0xFF2A331E)
val emeraldtertiaryContainerDark = Color(0xFF404A33)
val emeraldonTertiaryContainerDark = Color(0xFFBCECE7)
val emeralderrorDark = Color(0xFFFFB4AB)
val emeraldonErrorDark = Color(0xFF690005)
val emeralderrorContainerDark = Color(0xFF93000A)
val emeraldonErrorContainerDark = Color(0xFFFFDAD6)
val emeraldbackgroundDark = Color(0xFF12140E)
val emeraldonBackgroundDark = Color(0xFFE2E3D8)
val emeraldsurfaceDark = Color(0xFF12140E)
val emeraldonSurfaceDark = Color(0xFFE2E3D8)
val emeraldsurfaceVariantDark = Color(0xFF44483D)
val emeraldonSurfaceVariantDark = Color(0xFFC5C8BA)
val emeraldoutlineDark = Color(0xFF8F9285)
val emeraldoutlineVariantDark = Color(0xFF44483D)
val emeraldscrimDark = Color(0xFF000000)
val emeraldinverseSurfaceDark = Color(0xFFE2E3D8)
val emeraldinverseOnSurfaceDark = Color(0xFF2F312A)
val emeraldinversePrimaryDark = Color(0xFF4C662B)
val emeraldsurfaceDimDark = Color(0xFF12140E)
val emeraldsurfaceBrightDark = Color(0xFF383A32)
val emeraldsurfaceContainerLowestDark = Color(0xFF0C0F09)
val emeraldsurfaceContainerLowDark = Color(0xFF1A1C16)
val emeraldsurfaceContainerDark = Color(0xFF1E201A)
val emeraldsurfaceContainerHighDark = Color(0xFF282B24)
val emeraldsurfaceContainerHighestDark = Color(0xFF33362E)



